name: Publish to git package repo
on:
  push:
    branches: [main]

jobs:
  build-and-publish:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: pnpm/action-setup@v3.0.0
        with:
          version: 7.4.0
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'pnpm'
          registry-url: https://npm.pkg.github.com/

      - name: Install dependancies
        run: pnpm install
      - name: Test
        run: pnpm test
      - name: Build
        run: pnpm build
      - name: Build types
        run: pnpm types

      - name: Publish
        run: pnpm run publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Push tags
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          pnpm push-tags
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Create release pull request
        uses: changesets/action@v1
        with:
          version: pnpm run version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
